---
swagger: "2.0"
info:
  description: "TOSCA Simple qUeRy sErvice (SURE). "
  version: "1.2.0"
  title: "tosca-sure"
  contact:
    email: "S.Koulouzis@uva.nl"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/tosca-sure/1.2.0"
schemes:
- "https"
- "http"
paths:
  /tosca_types:
    get:
      description: "returns types"
      operationId: "get_type_definition"
      produces:
      - "application/json"
      parameters:
      - name: "query"
        in: "query"
        description: "the query to run on the DB"
        required: false
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/NodeTemplate"
        "404":
          description: "Not found"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "sure_tosca.controllers.default_controller"
    post:
      summary: ""
      description: "s"
      operationId: "add_type_definition"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "definition_map"
        required: true
        schema:
          type: "object"
          example:
            nodes: "https://raw.githubusercontent.com/skoulouzis/CONF/develop/TOSCA/types/nodes.yaml"
            data: "https://raw.githubusercontent.com/skoulouzis/CONF/develop/TOSCA/types/data.yml"
            capabilities: "https://raw.githubusercontent.com/skoulouzis/CONF/develop/TOSCA/types/capabilities.yaml"
            policies: "https://raw.githubusercontent.com/skoulouzis/CONF/develop/TOSCA/types/policies.yaml"
            interfaces: "https://raw.githubusercontent.com/skoulouzis/CONF/develop/TOSCA/types/interfaces.yml"
          additionalProperties:
            type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "sure_tosca.controllers.default_controller"
  /tosca_template:
    post:
      summary: "upload a tosca template description file"
      description: "upload and validate a tosca template description file"
      operationId: "upload_tosca_template"
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "file"
        in: "formData"
        description: "tosca Template description"
        required: true
        type: "file"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "sure_tosca.controllers.default_controller"
  /tosca_template/{id}:
    get:
      description: ""
      operationId: "get_tosca_template"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of topolog template uplodaed"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ToscaTemplate"
        "404":
          description: "Not found"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "sure_tosca.controllers.default_controller"
  /tosca_template/{id}/topology_template/node_templates:
    get:
      description: "returns nodes templates in topology"
      operationId: "get_node_templates"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of topolog template uplodaed"
        required: true
        type: "string"
      - name: "query"
        in: "query"
        description: "The the query"
        required: false
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/NodeTemplateMap"
        "404":
          description: "Not found"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "sure_tosca.controllers.default_controller"
definitions:
  NodeTemplate:
    type: "object"
    properties:
      derived_from:
        type: "string"
      properties:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      requirements:
        type: "array"
        items:
          type: "object"
          additionalProperties:
            type: "object"
            properties: {}
      interfaces:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      capabilities:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      type:
        type: "string"
      description:
        type: "string"
      directives:
        type: "array"
        items:
          type: "string"
      attributes:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      artifacts:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
    example:
      requirements:
      - key: "{}"
      - key: "{}"
      interfaces:
        key: "{}"
      capabilities:
        key: "{}"
      directives:
      - "directives"
      - "directives"
      derived_from: "derived_from"
      description: "description"
      attributes:
        key: "{}"
      type: "type"
      properties:
        key: "{}"
      artifacts:
        key: "{}"
  ToscaTemplate:
    type: "object"
    properties:
      tosca_definitions_version:
        type: "string"
      tosca_default_namespace:
        type: "string"
      template_name:
        type: "string"
      topology_template:
        $ref: "#/definitions/TopologyTemplate"
      template_author:
        type: "string"
      template_version:
        type: "string"
      description:
        type: "string"
      imports:
        type: "array"
        items:
          type: "object"
          additionalProperties:
            type: "object"
            properties: {}
      dsl_definitions:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      node_types:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      relationship_types:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      relationship_templates:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      capability_types:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      artifact_types:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      data_types:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      interface_types:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      policy_types:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      group_types:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      repositories:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
    example:
      node_types:
        key: "{}"
      policy_types:
        key: "{}"
      topology_template:
        outputs:
          key: "{}"
        substitution_mappings:
          key: "{}"
        inputs:
          key: "inputs"
        node_templates:
          key:
            requirements:
            - key: "{}"
            - key: "{}"
            interfaces:
              key: "{}"
            capabilities:
              key: "{}"
            directives:
            - "directives"
            - "directives"
            derived_from: "derived_from"
            description: "description"
            attributes:
              key: "{}"
            type: "type"
            properties:
              key: "{}"
            artifacts:
              key: "{}"
        policies:
        - key: "{}"
        - key: "{}"
        description: "description"
        groups:
          key: "{}"
        relationship_templates:
          key: "{}"
      template_version: "template_version"
      imports:
      - key: "{}"
      - key: "{}"
      template_author: "template_author"
      group_types:
        key: "{}"
      description: "description"
      template_name: "template_name"
      artifact_types:
        key: "{}"
      capability_types:
        key: "{}"
      repositories:
        key: "{}"
      tosca_definitions_version: "tosca_definitions_version"
      dsl_definitions:
        key: "{}"
      interface_types:
        key: "{}"
      relationship_types:
        key: "{}"
      tosca_default_namespace: "tosca_default_namespace"
      relationship_templates:
        key: "{}"
      data_types:
        key: "{}"
  TopologyTemplate:
    type: "object"
    properties:
      description:
        type: "string"
      inputs:
        type: "object"
        additionalProperties:
          type: "string"
      node_templates:
        type: "object"
        additionalProperties:
          $ref: "#/definitions/NodeTemplate"
      relationship_templates:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      outputs:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      groups:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      substitution_mappings:
        type: "object"
        additionalProperties:
          type: "object"
          properties: {}
      policies:
        type: "array"
        items:
          type: "object"
          additionalProperties:
            type: "object"
            properties: {}
    example:
      outputs:
        key: "{}"
      substitution_mappings:
        key: "{}"
      inputs:
        key: "inputs"
      node_templates:
        key:
          requirements:
          - key: "{}"
          - key: "{}"
          interfaces:
            key: "{}"
          capabilities:
            key: "{}"
          directives:
          - "directives"
          - "directives"
          derived_from: "derived_from"
          description: "description"
          attributes:
            key: "{}"
          type: "type"
          properties:
            key: "{}"
          artifacts:
            key: "{}"
      policies:
      - key: "{}"
      - key: "{}"
      description: "description"
      groups:
        key: "{}"
      relationship_templates:
        key: "{}"
  NodeTemplateMap:
    type: "object"
    properties:
      name:
        type: "string"
      nodeTemplate:
        $ref: "#/definitions/NodeTemplate"
    example:
      name: "name"
      nodeTemplate:
        requirements:
        - key: "{}"
        - key: "{}"
        interfaces:
          key: "{}"
        capabilities:
          key: "{}"
        directives:
        - "directives"
        - "directives"
        derived_from: "derived_from"
        description: "description"
        attributes:
          key: "{}"
        type: "type"
        properties:
          key: "{}"
        artifacts:
          key: "{}"
